---
- name: Ensure Monitoring user home directory exists
  ansible.builtin.file:
    path: "{{ monitoring_service_home }}/.config/containers/systemd/configs"
    state: directory
    owner: "{{ monitoring_service_user }}"
    mode: "0755"

- name: Deploy Monitoring Quadlet files (container, volume, network)
  ansible.builtin.copy:
    src: "{{ monitoring_service_role_dir }}/../../quadlets/"
    dest: "{{ monitoring_service_home }}/.config/containers/systemd/"
    owner: "{{ monitoring_service_user }}"
    mode: "0644"
    directory_mode: "0755"

- name: Reload systemd user daemon for Monitoring
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  become: yes
  become_user: "{{ monitoring_service_user }}"
